
const MOST_POPULAR_CURR = ['USD', 'EUR', 'CAD', 'INR', 'AED', 'JPY', 'CNY', 'BRL', 'COP', 'ARS']

const TYPE = {
  PAGE_NAME: 'PAGE_NAME',
  CURRENCIES: 'CURRENCIES',
  AMOUNT: 'AMOUNT',
  IS_CUR_AMOUNT_VALID: 'IS_CUR_AMOUNT_VALID',
  CURR_FROM_CURRENCY_RATES: 'CURR_FROM_CURRENCY_RATES',
  FROM: "FROM",
  TO: "TO"
};

export {
  TYPE,
  MOST_POPULAR_CURR
};
